apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    version: 1
    editable: false
# datasources:
  - name: 'Prometheus'
    access: 'proxy'
    editable: true
    is_default: true
    org_id: 1
    type: 'prometheus'
    url: 'http://prometheus:9090'
    version: 1